## Simple Network

In [1]:
def neural_net(input, weight):
    pred = input * weight
    return pred

In [2]:
# implementation inputs

inputs = [8.5, 9.5, 10, 9]

weight = 0.1
input = inputs[0]

pred = neural_net(input, weight)

print(pred)

0.8500000000000001


In [3]:
# implementation multiple inputs

def w_sum(a,b):
    assert len(a) == len(b)
    output = 0
    for i in range(len(a)):
        output += a[i] * b[i]

    return output


def neural_net(input, weight):
    pred = w_sum(input, weight)
    return pred


weights = [0.1, 0.2, 0]

#toes = current average number of toes per player
#wlrec = current games won (percent)
#nfans = fan count (in millions).

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = [toes[0],wlrec[0],nfans[0]]
pred = neural_net(input,weights)

print(pred)

0.9800000000000001


### vector Maths

In [4]:
def elementwise_multiplication(vec_a, vec_b):
    assert len(vec_a) == len(vec_b)
    output =  []

    for i in range(len(vec_a)):
        output[i] = vec_a[i] * vec_b[i]

    return output



def elementwise_addition(vec_a, vec_b):
    assert len(vec_a) == len(vec_b)
    output =  []

    for i in range(len(vec_a)):
        output[i] = vec_a[i] + vec_b[i]

    return output


def vector_sum(vec_a):
    output =  0

    for num in vec_a:
        output += num

    return output


def vector_average(vec_a):
    return vector_sum(vec_a)/len(vec_a)

### Implementation with numpy

In [5]:
import numpy as np

weights = [0.1, 0.2, 0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
inputs = [toes[0],wlrec[0],nfans[0]]

weights = np.array(weights)
toes = np.array(toes)
wlrec = np.array(wlrec)
nfans = np.array(nfans)
inputs = np.array(inputs)


def neural_net(inputs, weights):
    pred =  np.dot(inputs, weights)
    return pred


pred = neural_net(input,weights)
print(pred)

0.9800000000000001


In [6]:
# implement multiple inputs on a two layers with 3 nodes each architecture

weights = [0.1, 0.2, 0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
inputs = [toes,wlrec,nfans]

inputs = np.array(inputs).T     # transpose to get the shape like a table, a column for each variable / node


                    # toes % win # fans
ih_wgt = np.array([
                    [0.1, 0.2, -0.1], # hid[0] hidden node 0
                    [-0.1,0.1, 0.9], # hid[1]   hidden node 1
                    [0.1, 0.4, 0.1]]).T # hid[2] hidden node 2   transpose to get a column for each node


                    # hid[0] hid[1] hid[2]
hp_wgt = np.array([
                    [0.3, 1.1, -0.3], # hurt?  prediction node 0
                    [0.1, 0.2, 0.0], # win?    prediction node 1
                    [0.0, 1.3, 0.1] ]).T # sad?  prediction node 2  transpose to get a column for each node

weights = np.array([ih_wgt, hp_wgt])  # just like the concatenation of 2 dataframes

                                    ### nb  np.array([a.T, b.T]) != np.array([a, b]).T


def neural_net(inputs, weights):
    hid = np.dot(inputs, weights[0])
    pred =  np.dot(hid, weights[1])
    return pred


pred = neural_net(inputs[0],weights)
print(pred)

[0.2135 0.145  0.5065]


## Error evaluation

In [7]:
# Error calculations

weight = 0.5
input =  0.5
goal_pred = 0.8

pred = input * weight

error_s =  (pred - goal_pred) ** 2

print(f"Prediction: {pred}\nError squared: {goal_pred}")

Prediction: 0.25
Error squared: 0.8


In [8]:
# Error distribution and backpropagation
weight = 0.5
input =  0.5
goal_pred = 0.8
step_amount = 0.001

def pred(input, weight):
    predtn = input * weight
    return predtn

def error_lst(pred_, goal_pred):
    error = pred_ - goal_pred
    error_s =  error ** 2
    return error, error_s

def f_learn(input, weight, goal_pred):
    #print(f"Input type: {type(input)}\nWeight type: {type(weight)}\n")
    predt = pred(input, weight)
    errors = error_lst(predt, goal_pred)
    print(f"Prediction: {predt}\nError: {errors[0]}\nError squared: {errors[1]}\n")
    return predt, errors

def back_prop(weight, step_amount, input, error):
    step = step_amount
    #step = error * step_amount
    print("------------------------------------ Upward adjustment ----------------------------------- ")
    w_up = weight + step
    w_up_f = f_learn(input, w_up, goal_pred)
    w_up_error = w_up_f[1][1]
    
    print("------------------------------------ downward adjustment ----------------------------------- ")
    w_down = weight - step
    w_down_f = f_learn(input, w_down, goal_pred)
    w_down_error = w_down_f[1][1]

    
    if w_up_error < w_down_error:
        print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% weight adjusted up %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n\n")
        return w_up
    elif w_up_error > w_down_error:
        print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% weight adjusted down %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n\n")
        return w_down
    else:
        print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% weight maintained %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n\n")
        return weight


def lean_complete(input, weight, goal_pred, step_amount):
    print("########################### Foward Pass ##########################")
    f_pass = f_learn(input, weight, goal_pred)
    f_pred = f_pass[0]
    error_init = f_pass[1]
    print("\n")

    print("########################### Back Propagation ##########################")
    n_weight = back_prop(weight, step_amount, input, error_init[0])
    return n_weight



for i in range(1101):
    print(f"----------------------------------- pass {i+1} -----------------------------------")
    prev_w = weight
    weight = lean_complete(input, weight, goal_pred, step_amount)

    if weight == prev_w:
        break

----------------------------------- pass 1 -----------------------------------
########################### Foward Pass ##########################
Prediction: 0.25
Error: -0.55
Error squared: 0.30250000000000005



########################### Back Propagation ##########################
------------------------------------ Upward adjustment ----------------------------------- 
Prediction: 0.2505
Error: -0.5495000000000001
Error squared: 0.3019502500000001

------------------------------------ downward adjustment ----------------------------------- 
Prediction: 0.2495
Error: -0.5505
Error squared: 0.30305024999999997

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% weight adjusted up %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



----------------------------------- pass 2 ----------------------------

In [13]:
# Error distribution and backpropagation
weight = 0.5
input =  0.5
goal_pred = 0.8
step_amount = 0.001

def pred(input, weight):
    predtn = input * weight
    return predtn

def error_lst(pred_, goal_pred):
    error = pred_ - goal_pred
    error_s =  error ** 2
    return error, error_s

def f_learn(input, weight, goal_pred):
    #print(f"Input type: {type(input)}\nWeight type: {type(weight)}\n")
    predt = pred(input, weight)
    errors = error_lst(predt, goal_pred)
    print(f"Prediction: {predt}\nError: {errors[0]}\nError squared: {errors[1]}\n")
    return predt, errors

def back_prop(weight, step_amount, input, error):
    #step = step_amount
    step = error * input
    adjusted_weight = weight - step
    return adjusted_weight


def lean_complete(input, weight, goal_pred, step_amount):
    print("########################### Foward Pass ##########################")
    f_pass = f_learn(input, weight, goal_pred)
    f_pred = f_pass[0]
    error_init = f_pass[1]
    print("\n")

    print("########################### Back Propagation ##########################\n\n\n")
    n_weight = back_prop(weight, step_amount, input, error_init[0])
    return n_weight



for i in range(20):
    print(f"----------------------------------- pass {i+1} -----------------------------------")
    prev_w = weight
    weight = lean_complete(input, weight, goal_pred, step_amount)

    if weight == prev_w:
        break

----------------------------------- pass 1 -----------------------------------
########################### Foward Pass ##########################
Prediction: 0.25
Error: -0.55
Error squared: 0.30250000000000005



########################### Back Propagation ##########################



----------------------------------- pass 2 -----------------------------------
########################### Foward Pass ##########################
Prediction: 0.3875
Error: -0.41250000000000003
Error squared: 0.17015625000000004



########################### Back Propagation ##########################



----------------------------------- pass 3 -----------------------------------
########################### Foward Pass ##########################
Prediction: 0.49062500000000003
Error: -0.309375
Error squared: 0.095712890625



########################### Back Propagation ##########################



----------------------------------- pass 4 -----------------------------------
#######################

### Build a model

In [55]:
# implement multiple inputs on a two layers with 3 nodes each architecture

weights = [0.1, 0.2, 0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
inputs = [toes,wlrec,nfans]

inputs = np.array(inputs).T     # transpose to get the shape like a table, a column for each variable / node


                    # toes % win # fans
ih_wgt = np.array([
                    [0.1, 0.2, -0.1], # hid[0] hidden node 0
                    [-0.1,0.1, 0.9], # hid[1]   hidden node 1
                    [0.1, 0.4, 0.1]]).T # hid[2] hidden node 2   transpose to get a column for each node


                    # hid[0] hid[1] hid[2]
hp_wgt = np.array([
                    [0.3, 1.1, -0.3], # hurt?  prediction node 0
                    [0.1, 0.2, 0.0], # win?    prediction node 1
                    [0.0, 1.3, 0.1] ]).T # sad?  prediction node 2  transpose to get a column for each node

weights = np.array([ih_wgt, hp_wgt])  # just like the concatenation of 2 dataframes

                                    ### nb  np.array([a.T, b.T]) != np.array([a, b]).T


def neural_net(inputs, weights):
    print(f'input: {inputs}, shape: {inputs.shape}\n weight: {weights[0]}, shape: {weights[0].shape}')
    hid = np.dot(inputs, weights[0])
    pred =  np.dot(hid, weights[1])
    return pred


pred = neural_net(inputs[0],weights)
print(pred)

input: [8.5  0.65 1.2 ], shape: (3,)
 weight: [[ 0.1 -0.1  0.1]
 [ 0.2  0.1  0.4]
 [-0.1  0.9  0.1]], shape: (3, 3)
[0.2135 0.145  0.5065]


In [172]:
# building a simple class for neural network implementation


# inputs, weights, hlayers = [num_nodes(int) for ly1 1,...]

class SimpleModel() :
    def __init__(self, inputs, layers):
        assert type(layers) == type(list())
        assert len(layers) > 0
        assert layers[0] == inputs.shape[1]

        self.w_lst = []
        prev_nodes = 0
        for n in range(len(layers)):
            # print(f'Prev_node : {prev_nodes}')
            n_nodes = layers[n]
            if prev_nodes == 0:
                self.w_lst.append(np.zeros(shape=(n_nodes,n_nodes)))
            else:
                self.w_lst.append(np.zeros(shape=(prev_nodes,n_nodes)))
            prev_nodes = n_nodes
                             
                
        # self.w_lst = [np.zeros(shape=(n,n)) for n in layers]
        self.inputs = inputs


    def f_pass(self, input_entry):
        # print(f'weight shape: {self.w_lst[0].shape}')
        # print(f'input shape: {input_entry.shape}')
        lyr = np.dot(input_entry.reshape(1,input_entry.shape[0]), self.w_lst[0])
        for i in range(len(self.w_lst)):
            # print(f'layer_output shape r{i}: {lyr.shape}') 
            # print(f'layer_output r{i}: {lyr}') 
            if i+1 == len(self.w_lst):
                break
            lyr = np.dot(lyr, self.w_lst[i+1])
        return lyr

    def show_weights(self):
        return repr(self.w_lst)

In [38]:
[np.zeros(shape=n) for n in [3,3]]

[array([0., 0., 0.]), array([0., 0., 0.])]

In [173]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
inputs = [toes,wlrec,nfans]

inputs = np.array(inputs).T

mdl = SimpleModel(inputs, [3,5,1,7])
#mdl.show_weights()
mdl.f_pass(inputs[0]).shape

Prev_node : 0
Prev_node : 3
Prev_node : 5
Prev_node : 1


(1, 7)

In [157]:
type({0:3,1:5})

dict

In [129]:
array1 = np.random.ranf(size=(3))
array2 = np.random.ranf(size=(4))

In [131]:
# array1.dot(array2.reshape(5,1)) == 
array1.dot(array2.T)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [98]:
np.random.ranf(size=(3))

array([0.56248891, 0.98308698, 0.31217604])

In [96]:
np.random.ranf(size=(3,2))

array([[0.2332947 , 0.69049274],
       [0.63250655, 0.82892738],
       [0.51082527, 0.22371424]])